<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test.....]]>
    </line>
    <line>
      <![CDATA[TestA.....]]>
    </line>
    <line>
      <![CDATA[TestB.....]]>
    </line>
  </reporter-output>
  <suite started-at="2018-09-26T09:44:43Z" name="Default suite" finished-at="2018-09-26T09:45:36Z" duration-ms="53518">
    <groups>
    </groups>
    <test started-at="2018-09-26T09:44:43Z" name="Default test" finished-at="2018-09-26T09:45:36Z" duration-ms="53518">
      <class name="script.TestDemo">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:44:43Z" name="openApplication" finished-at="2018-09-26T09:44:58Z" duration-ms="15477" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="test()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:44:58Z" name="test" finished-at="2018-09-26T09:44:58Z" duration-ms="8" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Test.....]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:44:58Z" name="CloseApplication" finished-at="2018-09-26T09:45:00Z" duration-ms="2176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
        <test-method is-config="true" signature="openApplication()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:45:00Z" name="openApplication" finished-at="2018-09-26T09:45:17Z" duration-ms="16521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="testA()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:45:17Z" name="testA" finished-at="2018-09-26T09:45:17Z" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.TestDemo.testA(TestDemo.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TestA.....]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:45:17Z" name="CloseApplication" finished-at="2018-09-26T09:45:19Z" duration-ms="2145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
        <test-method is-config="true" signature="openApplication()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:45:19Z" name="openApplication" finished-at="2018-09-26T09:45:34Z" duration-ms="15012" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="testB()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:45:34Z" name="testB" finished-at="2018-09-26T09:45:34Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.TestDemo.testB(TestDemo.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TestB.....]]>
            </line>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:script.TestDemo@2a266d09]" started-at="2018-09-26T09:45:34Z" name="CloseApplication" finished-at="2018-09-26T09:45:36Z" duration-ms="2123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
      </class> <!-- script.TestDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
